Gx3 4620 ⚡️ tools qa elements radio buttons
upex-galaxy/upex-cypress-demo pull request #695
Opened 2024-08-12 02:05 UTC by DonnaCas

Se confirma la terminación de las pruebas realizadas y se requiere hace merge a la rama ppal.

2024-08-13 20:05 UTC, AlexanderWindecker commented
Hola Donna como estas, espero te encuentres bien. Te deje unas correcciones.

Saludos.-

2024-08-15 16:30 UTC, DonnaCas commented
Muy buen día @AlexanderWindecker,  corregí lo que me indicaste anteriormente, serrías tan formal de revisar nuevamente, mil gracias

2024-08-16 00:07 UTC, saiotest requested changes
Dejé un mensaje en el archivo package-lock.json para solicitar cambios urgentes
@DonnaCas @AlexanderWindecker

2024-08-16 00:07 UTC, saiotest commented on package-lock.json
Solicito que se ELIMINE este archivo antes de mergear, esto se debe al uso de:
`npm install` 
y la idea es usar `yarn install`
@DonnaCas @AlexanderWindecker

2024-08-16 19:38 UTC, AlexanderWindecker approved these changes

2024-08-16 19:46 UTC, AlexanderWindecker approved these changes

2024-08-16 19:49 UTC, AlexanderWindecker approved these changes
todo ok

2024-08-16 23:19 UTC, saiotest approved these changes

2024-08-16 23:20 UTC, merged