Test/gx3 5540 ⚡️ tools qa elements text box fill form and submit
upex-galaxy/upex-cypress-demo pull request #727
Opened 2024-10-29 22:32 UTC by briangermano98

# **Nomenclatura del Título del Pull Request**

> "Test(`GX3-5540`): `ToolsQA | Elements | Text Box: Fill form and Submit`"

## Feature to be Test Automated

- `GX3-5540`: [ToolsQA | Elements | Text Box: Fill form and Submit](https://upexgalaxy47.atlassian.net/browse/GX3-5540)

## Summary of Changes

Se agregaron 7 casos de prueba para el eficiente desempeño de fill form and submit

## Test Results Verification

https://github.com/user-attachments/assets/f8887ae5-b53a-4404-9fe0-21a66f6995a9

## Git Log

```bash
commit e0c14bd3b7c3ab5649aa52cacaa1999a84e82ebd (HEAD -> test/GX3-5540-⚡️-tools-qa-elements-text-box-fill-form-and-submit, origin/test/GX3-5540-⚡️-tools-qa-elements-text-box-fill-form-and-submit)
Author: Brian Germano <taylor.brayan@hotmail.com>
Date:   Tue Oct 29 18:47:01 2024 -0300
```

## Observations

## Checklist

- [x] Mi código sigue las pautas de estilo de este proyecto, revisando la nomenclatura usada y corregiendo cualquier error ortográfico.

- [x] He realizado una revisión doble de mi propio código y he comentado especialmente en áreas difíciles de entender.

- [x] Las pruebas automatizadas nuevas y existentes pasan localmente y he comprobado que mi código funciona sin generar nuevas advertencias (IMPORTANTE)

- [x] He ejecutado el Pipeline de "Sanity Test" específicamente para importar mis Resultados de Prueba a Jira y he comprobado así que mi código de prueba funciona también en CI (IMPORTANTE)

- [x] Confirmo que he considerado agregar documentación nueva al proyecto (en la carpeta `docs/`) en caso de ser necesario. Véase en la descripción del PR si he agregado o no.

2024-10-30 18:44 UTC, AlexanderWindecker commented
Hola Brian, se anima a realizar un constructor en page en vez de usar "get"

2024-11-02 03:32 UTC, briangermano98 commented
Hola Ale, después de mucho esmero se logró la consigna.

2024-11-04 16:41 UTC, AlexanderWindecker commented
Hola Brian, disculpa la demora. Te deje nuevos comentarios. A poner en practica y mejorar el código. Excelente trabajo aguardo los cambios para mejoras y vuelve a pushear

Saludos.-

2024-11-06 23:01 UTC, briangermano98 commented
Utilize el constructor en ambas historias como decía los comentarios.

2024-11-06 23:14 UTC, AlexanderWindecker commented
Hola Brian, la rama es 5540, y no veo cambios en los test.

2024-11-07 23:21 UTC, briangermano98 commented
Hola Alexander hice los cambios. Cualquier recomendación sera bienvenida y tenida en cuenta.

2024-11-08 13:52 UTC, AlexanderWindecker commented
Hola Brian, realmente no veo los cambios realizados en la rama y en el test.

2024-11-11 15:22 UTC, AlexanderWindecker commented on cypress/support/pages/GX3-5376-Selectable.Page.js
> +
Hola Brian, te animas a incorporar un constructor en vez de "get".

2024-11-11 15:22 UTC, AlexanderWindecker commented on cypress/support/pages/GX3-5540-textbox.Page.js
> +
Bien trabajado. Me gusta que hayas investigado y simplificado el código. Aquí tienes una versión ligeramente ajustada para que sea más clara y fácil de mantener:

```
constructor() {
this.fullNameInput = () => cy.get('#userName');
}

// Accion

enterFullName(name) {
		this.fullNameInput.type(name);
	}
```

2024-11-11 15:22 UTC, AlexanderWindecker commented on cypress/e2e/Tests/Elements/GX3-5540-textbox.cy.js
> +import { textBoxPage } from '../../../support/pages/GX3-5540-textbox.Page';
Buen trabajo. Un pequeño ajuste para que el código sea más limpio: el repositorio está configurado con @pages, lo cual te permite importar directamente desde esa ruta en lugar de usar múltiples ../... Esto facilita la legibilidad y señority. Vas a quedar crack frente a los devs.

```
import { textBoxPage } from '@pages/GX3-5540-textbox.Page';

```

2024-11-11 15:22 UTC, AlexanderWindecker commented on cypress/e2e/Tests/Elements/GX3-5540-textbox.cy.js
> +
Buen trabajo con la estructura de los tests. Una recomendación: en lugar de agrupar todas las acciones antes de validar, podemos aplicar la secuencia acción -> validación para cada campo. Así, cada acción tendrá una verificación rápida mediante should, lo que facilita identificar errores específicos.

¿Puedes refactorizarlo?

```
textBoxPage.enterFullName(the.FullName.data.valid).should('have.value', the.FullName.data.valid);
textBoxPage.enterEmail(the.Email.data.valid).should('have.value', the.Email.data.valid);
```

2024-11-11 15:22 UTC, AlexanderWindecker commented on cypress/support/pages/GX3-5540-textbox.Page.js
> +	verifyOutput(name, email, currentAddress, permanentAddress) {
En POM, nos enfocamos en las acciones y localizadores sin añadir validaciones. Las verificaciones, como should se realizan en el test.

2024-11-24 19:30 UTC, ZwitterKaneda commented
Hola @briangermano98, hola @AlexanderWindecker . Estaré revisando el PR para darle flujo

2024-11-24 19:32 UTC, ZwitterKaneda commented on cypress/e2e/Tests/Elements/GX3-5540-textbox.cy.js
> +import { textBoxPage } from '../../../support/pages/GX3-5540-textbox.Page';
Tal cual como dice Alex, el uso de los alias permiete una mejor legitibilidad en el código =) y en caso de mover el archivo no necesitarás corregir el path ya que se usará el alias

2024-11-24 19:54 UTC, ZwitterKaneda requested changes
Tienes archivos dentro del pull request que corresponden a otro test. Deberás de quitarlos de aquí para poder proseguir con la integración de este PR.

Si quieres integrar los cambios al otro test, te sugiero abrir la branch de ese test y enviarlos desde ahí como mejora. Concidera lo del cy.root() que te comenté.

Por todo el resto de tu trabajo, muy bien logrado 👏

2024-11-24 19:54 UTC, ZwitterKaneda commented on cypress/e2e/Tests/Interactions/GX3-5376-Selectable.cy.js
Este archivo corresponde a otro test. Los cambios realizados no deberían de estar aquí, sino con el código correspondiente al test 5376

2024-11-24 19:54 UTC, ZwitterKaneda commented on cypress/e2e/Tests/Interactions/GX3-5376-Selectable.cy.js
> +		cy.root().find(selectablePage.listButton).should('have.class', 'active');
el uso de `cy.root()` en este contexto. No es una buena práctica por varias razones:
Es demasiado genérico y poco específico... es similar a usar cy.get('*'), lo cual puede hacer que el test sea:
Más frágil ante cambios en la estructura del DOM
Menos explícito sobre qué elemento realmente queremos probar
Más lento en la ejecución al tener que buscar en todo el árbol DOM
y otra cosa para "sumarle" al motivo de que no debería de estar en este tipo de test, viola el principio de que los tests deberían ser lo más específicos y claros posible.

2024-11-24 19:54 UTC, ZwitterKaneda commented on cypress/support/pages/GX3-5376-Selectable.Page.js
este archivo corresponde a otro test. no debería de estar aquí =)

2024-11-24 19:54 UTC, ZwitterKaneda commented on cypress/support/pages/GX3-5540-textbox.Page.js
Vi tu código y quiero comentarte algunas cosas sobre POM en Cypress. Mira, hay muchas formas de trabajar con este patrón y la estructuración de tu clase va a depender del tipo de proyecto en el que estés.
Como ya mencionó @AlexanderWindecker , te recomendaría modificar el constructor para que contenga el elemento HTML completo y no solo el ID. Esto trae dos beneficios importantes:
```
constructor() {
    this.fullNameInput = () => cy.get('#userName');
    this.emailInput = () => cy.get('#userEmail');
    this.currentAddressInput = () => cy.get('#currentAddress');
    this.permanentAddressInput = () => cy.get('#permanentAddress');
    this.submitButton = () => cy.get('#submit');
}
```
Las ventajas son claras:

Al devolver directamente el elemento de Cypress, encapsulas mejor la lógica de selección
Cada selector retorna una cadena de Cypress lista para usar

Y mira cómo quedarían los métodos - esto es lo interesante:
```
// Método genérico para escribir en cualquier input
type(element, value) {
    element().type(value);
}

// Métodos para verificar valores y estados
verifyOutput(element, value) {
    element().should('have.value', value);
}

verifyNoOutput(element) {
    element().should('not.have.value');
}

verifyError(element) {
    element().should('have.class', 'field-error');
}

// Y acá usamos los métodos genéricos para acciones específicas
enterFullName(name) {
    this.type(this.fullNameInput, name);
}

enterEmail(email) {
    this.type(this.emailInput, email);
}
```
Este enfoque tiene varias ventajas:

Tu código queda más mantenible y DRY (Don't Repeat Yourself)
Mejor encapsulación de la lógica de Cypress
Es más fácil de testear y debuggear (Esto es algo en lo que se va trabajando con el tiempo)
Y lo más importante: sigue las mejores prácticas recomendadas de Cypress (puedes verlas en la documentación y en varios videos del framework)

2024-11-24 19:55 UTC, ZwitterKaneda commented
Se volverá a revisar el código en un nuevo Pull request. Ante cualquier duda puedes escribirme por slack o en el canal de #automation-cypress

2024-11-24 19:55 UTC, closed without merging